finchcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main_app.urls')),
    path("admin/", admin.site.urls),
]

main_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
  path('', views.home, name='home'),
  # django's convention is to use a trailing / for
  # the routE
  path('about/', views.about, name='about'),
  path('finches/', views.finches_index, name="index"),
  path('finches/<int:finch_id>/', views.finches_detail, name='detail'),
  path('finches/create/', views.FinchCreate.as_view(), name='finches_create'),
# CBV's expect the params to be called pk (convention), which is short for primary key, 
# which is another for id
  path('finches/<int:pk>/update/', views.FinchUpdate.as_view(), name='finches_update'),
  path('finches/<int:pk>/delete/', views.FinchDelete.as_view(), name='finches_delete'),
  path('finches/<int:finch_id>/add_feeding/', views.add_feeding, name='add_feeding'),
  path('finches/<int:finch_id>/assoc_toy/<int:toy_id>/', views.assoc_toy, name='assoc_toy'),
  path('toys/', views.ToyList.as_view(), name='toys_index'),
  path('toys/<int:pk>/', views.ToyDetail.as_view(), name='toys_detail'),
  path('toys/create/', views.ToyCreate.as_view(), name='toys_create'),
  path('toys/<int:pk>/update/', views.ToyUpdate.as_view(), name='toys_update'),
  path('toys/<int:pk>/delete/', views.ToyDelete.as_view(), name='toys_delete'),
]

main_app/models.py
from django.db import models
from django.urls import reverse


class Toy(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('toys_detail', kwargs={'pk': self.id})

class Finch(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    toys = models.ManyToManyField(Toy)


    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
      return reverse('detail', kwargs={'finch_id': self.id})
    
MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)


class Feeding(models.Model):
    date = models.DateField('feeding date')
    meal = models.CharField(
        max_length=1,
        # add the 'choices' field option
        choices=MEALS,
        # set the default value for meal to be 'B'
        default=MEALS[0][0]
    )

    finch = models.ForeignKey(Finch, on_delete=models.CASCADE)
    def __str__(self):
        # Nice method for obtaining the friendly value of a Field.choice
        return f"{self.get_meal_display()} on {self.date}"

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
	class Meta:
		# meta class is configuration options for a class
		# this is straight from the docs
		model = Feeding
		fields = ['date', 'meal']

main_app/views.py
from django.shortcuts import render, redirect

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
# from the ./models import Finch
from .models import Finch, Toy
from .forms import FeedingForm



def home(request):
	finches = Finch.objects.all()
	return render(request, 'home.html')

def about(request):
	return render(request, 'about.html')



def assoc_toy(request, finch_id, toy_id):
	print(finch_id, toy_id )
	finch = Finch.objects.get(id=finch_id)
	finch.toys.add(toy_id)# adding a row to our through table the one with 2 foriegn keys in sql
	return redirect('detail', finch_id=finch_id)

class FinchCreate(CreateView):
	model = Finch
	fields = '__all__'


class FinchUpdate(UpdateView):
	model = Finch
	# disallow renaming of the cat
	fields = ['breed', 'description', 'age']
	# uses def get_absolute_url in models.py to redirect the put request
	# back to the the detail page of the cat just updated

class FinchDelete(DeleteView):
	model = Finch
	# define the success_url here because the def get_absolute_url in the models.property
	# redirects to a detail page which doesn't make sense since we deleted it
	success_url = '/finches' # redirect to cats_index path


def finches_index(request):
	# tell the model to find all the rows in the cats table!
	finches = Finch.objects.all()
	return render(request, 'finches/index.html', {
		'finches': finches
		#'cats' becomes a variable name in 'cats/index.html'
		# just like express 
		# res.render('cats/index', {'cats': cats})
  })


# cat_id comes from the path in the urls.py 
# path('cats/<int:cat_id>/', views.cats_detail, name='detail'),
def finches_detail(request, finch_id):
	# tell the model to find the row that matches cat_id from the request in the database
	finch = Finch.objects.get(id=finch_id)
	id_list = finch.toys.all().values_list('id')
	# Now we can query the toys table for a the toys 
	# that are not in the id_list!     field looksup in django (google this)
	toys_finch_doesnt_have = Toy.objects.exclude(id__in=id_list)

	# instatiate the feeding form class to create an instance of the class
	# in otherwords a form object
	feeding_form = FeedingForm()
	return render(request, 'finches/detail.html', {
		'finch': finch,
		'feeding_form': feeding_form,
		'toys': toys_finch_doesnt_have

	})

# 'cats/<int:cat_id>/add_feeding/'
def add_feeding(request, finch_id):
	# process the form request form the client
	form = FeedingForm(request.POST)
	# request.POST is like req.body, its the contents of the form
	# validate the form
	if form.is_valid():
		# create an in memory instance (on django) of our data
		# to be added to psql, commit=False, don't save to db yet
		new_feeding = form.save(commit=False)
		# now we want to make sure we add the cat id to the new_feeding
		new_feeding.finch_id = finch_id
		new_feeding.save() # this is adding a feeding row to the feeding table in psql
	return redirect('detail', finch_id=finch_id) #cat_id is the name of the param in the url path, 
	# cat_id, is the id of the cat from the url request

class ToyList(ListView):
    model = Toy


class ToyDetail(DetailView):
    model = Toy


class ToyCreate(CreateView):
    model = Toy
    fields = '__all__'


class ToyUpdate(UpdateView):
    model = Toy
    fields = ['name', 'color']


class ToyDelete(DeleteView):
    model = Toy
    success_url = '/toys/'

main_app/templates/about.html
{% extends 'base.html' %}


{% block content %}
	<h1>About the Finch Collector</h1>
	<hr>
	<p>Hire the Finch Collector!</p>
{% endblock content %}
	

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Finch Collector</title>
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <head>
  
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Finch Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'toys_create' %}">Add a Toy</a></li>
          <li><a href="{% url 'toys_index' %}">View All Toys</a></li>
          <li><a href="{% url 'finches_create' %}">Add a Finch</a></li>
          <li><a href="{% url 'index' %}">View All My Finches</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2021 Finch Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/finches/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Finch Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ finch.name }}</span>
        <p>Breed: {{ finch.breed }}</p>
        <p>Description: {{ finch.description|linebreaks }}</p>
        {% if finch.age > 0 %}
          <p>Age: {{ finch.age }}</p>
        {% else %}
          <p>Age: Kitten</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'finches_update' finch.id %}">Edit</a>
        <a href="{% url 'finches_delete' finch.id %}">Delete</a>
      </div>
    </div>
  </div>
  <!-- New Markup Below -->
  <div class="col s6">

    <form action="{% url 'add_feeding' finch.id %}" method="POST">
      {% csrf_token %}

      {{ feeding_form.as_p }}
      <input type="submit" class="btn" value="Add Feeding">
    </form>

      <table class="striped">
      <thead>
        <tr><th>Date</th><th>Meal</th></tr>
      </thead>
      <tbody>
        {% for feeding in finch.feeding_set.all %}
          <tr>
            <td>{{feeding.date}}</td>
            <td>{{feeding.get_meal_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <!-- New Markup Above -->
</div>

<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ finch.name }}'s Toys</h3>
    {% if finch.toys.count %}
      {% for toy in finch.toys.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Toys 😿</h5>
    {% endif %}
  </div>
  <!-- Available toys will come after this line -->
  <div class="col s6">
    <h3>Available Toys</h3>
    {% if toys.count %}
      {% for toy in toys.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_toy' finch.id toy.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{cat.name}} Already Has All Toys Available</h5>
    {% endif %}
  </div>
</div>

<script>
const dateEl = document.querySelector('#id_date')
M.Datepicker.init(dateEl, {
  format: 'yyyy-mm-dd',
  defaultDate: new Date(),
  setDefaultDate: true,
  autoClose: true,
 
})

const selectEl = document.querySelector('#id_meal')
M.FormSelect.init(selectEl, {
  classes: 'green darken-2-text'
})
</script>


{% endblock %}

main_app/templates/finches/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Finch List</h1>

{% for finch in finches %}
  <div class="card">
    <a href="{% url 'detail' finch.id %}">
      <div class="card-content">
        <span class="card-title">{{ finch.name }}</span>
        <p>Breed: {{ finch.breed }}</p>
        <p>Description: {{ finch.description }}</p>
        {% if finch.age > 0 %}
          <p>Age: {{ finch.age }}</p>
        {% else %}
          <p>Age: Finch</p>
        {% endif %}
      </div>
    </a>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}


{% block content %}
<h1>home</h1>	
	
{% endblock content %}

	

main_app/templates/main_app/finch_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Finch</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' finch.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/finch_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Finch</h1>
{% endif %}

  <h1>Add Finch</h1>
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
  
{% endblock %}

main_app/templates/main_app/toy_confirm_delete.html
   
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Toy</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'toys_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/toy_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Toy Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ toy.name }}</span>
        <p>Color: {{ toy.color }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'toys_update' toy.id %}">Edit</a>
        <a href="{% url 'toys_delete' toy.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/toy_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Toy</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
	<!-- Django requires the following for security purposes -->
	{% csrf_token %}
	<table>
		<!-- Render the inputs inside of <tr>s & <td>s -->
		{{ form.as_table }}
	</table>
	<input type="submit" value="Submit!" class="btn">
</form>
{% endblock %}

main_app/templates/main_app/toy_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Toy List</h1>

<!-- you get two variables in the list page (index page) -->

<!-- <model_name>_list 
object_list -->

<!-- toy_list 
object_list -->

{% for toy in toy_list %}
  <a href="{% url 'toys_detail' toy.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ toy.name }}</span>
            <p>Color: {{ toy.color }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}